[package]
name = "pandit"
version = "0.1.0"
authors = ["Peter Parkanyi <p@symmetree.dev>", "Junyeong Jeong <rhdxmr@gmail.com>"]
edition = "2018"
repository = "https://github.com/foniod/redbpf"
description = "Example probes for redBPF"
license = "MIT OR Apache-2.0"
keywords = ["bpf", "ebpf", "build", "bindgen", "redbpf"]
publish = false

[dependencies]
probes = { path = "./probes", package = "probes" }
libc = "0.2"
tokio = { version = "^1.0.1", features = ["rt", "signal", "time", "io-util", "net", "sync"] }
tokio-test = "0.4.2"
redbpf = { version = "2.2.0", features = ["load"] }
futures = "0.3"
tracing = "0.1.26"
serde_json = "1.0"
tracing-subscriber = "0.3.2"
httparse = "1.5.1"
dashmap = "4.0.2"
protobuf = { git = "https://github.com/stepancheg/rust-protobuf.git", branch = "master", features = ["with-bytes"] }
protoc-rust = "2.25.2"
protobuf-parse = { git = "https://github.com/stepancheg/rust-protobuf.git", branch = "master" }


[lib]
path = "src/lib.rs"

[[bin]]
name = "pandit"
path = "src/main.rs"
required-features = ["kernel5_8"]  # bpf iterator has been supported since kernel v5.8

[features]
kernel5_8 = []

# [workspace]
# members = ["probes"]