[package]
name = "pandit"
version = "0.1.0"
authors = ["Peter Parkanyi <p@symmetree.dev>", "Junyeong Jeong <rhdxmr@gmail.com>"]
edition = "2018"
repository = "https://github.com/foniod/redbpf"
description = "Example probes for redBPF"
license = "MIT OR Apache-2.0"
keywords = ["bpf", "ebpf", "build", "bindgen", "redbpf"]
publish = false

[build-dependencies]
cargo-bpf = { version = "2.2.0", default-features = false, features = ["build"] }

[dependencies]
probes = { path = "./bpf", package = "pandit-bpf" }
libc = "0.2"
tokio = { version = "^1.0.1", features = ["rt", "signal", "time", "io-util", "net", "sync"] }
redbpf = "2.2.0"
futures = "0.3"
tracing = "0.1.26"
tracing-subscriber = "0.3.2"

[[bin]]
name = "pandit"
path = "src/main.rs"
required-features = ["kernel5_8"]  # bpf iterator has been supported since kernel v5.8

[features]
kernel5_8 = []
default = ["llvm13"]
llvm13 = ["cargo-bpf/llvm13"]