// This file is generated by rust-protobuf 3.0.0-alpha.2. Do not edit
// .proto file is parsed by protoc --rust-out=...
// @generated

// https://github.com/rust-lang/rust-clippy/issues/702
#![allow(unknown_lints)]
#![allow(clippy::all)]

#![allow(unused_attributes)]
#![cfg_attr(rustfmt, rustfmt::skip)]

#![allow(box_pointers)]
#![allow(dead_code)]
#![allow(missing_docs)]
#![allow(non_camel_case_types)]
#![allow(non_snake_case)]
#![allow(non_upper_case_globals)]
#![allow(trivial_casts)]
#![allow(unused_results)]
#![allow(unused_mut)]

//! Generated file from `http.proto`

/// Generated files are compatible only with the same version
/// of protobuf runtime.
const _PROTOBUF_VERSION_CHECK: () = ::protobuf::VERSION_3_0_0_ALPHA_2;

#[derive(PartialEq,Clone,Default)]
pub struct API {
    // message fields
    pub content_type: ::std::string::String,
    // message oneof groups
    pub pattern: ::std::option::Option<api::Pattern>,
    // special fields
    pub unknown_fields: ::protobuf::UnknownFields,
    pub cached_size: ::protobuf::rt::CachedSize,
}

impl<'a> ::std::default::Default for &'a API {
    fn default() -> &'a API {
        <API as ::protobuf::Message>::default_instance()
    }
}

impl API {
    pub fn new() -> API {
        ::std::default::Default::default()
    }

    // string get = 50001;

    pub fn get_get(&self) -> &str {
        match self.pattern {
            ::std::option::Option::Some(api::Pattern::get(ref v)) => v,
            _ => "",
        }
    }

    pub fn clear_get(&mut self) {
        self.pattern = ::std::option::Option::None;
    }

    pub fn has_get(&self) -> bool {
        match self.pattern {
            ::std::option::Option::Some(api::Pattern::get(..)) => true,
            _ => false,
        }
    }

    // Param is passed by value, moved
    pub fn set_get(&mut self, v: ::std::string::String) {
        self.pattern = ::std::option::Option::Some(api::Pattern::get(v))
    }

    // Mutable pointer to the field.
    pub fn mut_get(&mut self) -> &mut ::std::string::String {
        if let ::std::option::Option::Some(api::Pattern::get(_)) = self.pattern {
        } else {
            self.pattern = ::std::option::Option::Some(api::Pattern::get(::std::string::String::new()));
        }
        match self.pattern {
            ::std::option::Option::Some(api::Pattern::get(ref mut v)) => v,
            _ => panic!(),
        }
    }

    // Take field
    pub fn take_get(&mut self) -> ::std::string::String {
        if self.has_get() {
            match self.pattern.take() {
                ::std::option::Option::Some(api::Pattern::get(v)) => v,
                _ => panic!(),
            }
        } else {
            ::std::string::String::new()
        }
    }

    // string put = 50002;

    pub fn get_put(&self) -> &str {
        match self.pattern {
            ::std::option::Option::Some(api::Pattern::put(ref v)) => v,
            _ => "",
        }
    }

    pub fn clear_put(&mut self) {
        self.pattern = ::std::option::Option::None;
    }

    pub fn has_put(&self) -> bool {
        match self.pattern {
            ::std::option::Option::Some(api::Pattern::put(..)) => true,
            _ => false,
        }
    }

    // Param is passed by value, moved
    pub fn set_put(&mut self, v: ::std::string::String) {
        self.pattern = ::std::option::Option::Some(api::Pattern::put(v))
    }

    // Mutable pointer to the field.
    pub fn mut_put(&mut self) -> &mut ::std::string::String {
        if let ::std::option::Option::Some(api::Pattern::put(_)) = self.pattern {
        } else {
            self.pattern = ::std::option::Option::Some(api::Pattern::put(::std::string::String::new()));
        }
        match self.pattern {
            ::std::option::Option::Some(api::Pattern::put(ref mut v)) => v,
            _ => panic!(),
        }
    }

    // Take field
    pub fn take_put(&mut self) -> ::std::string::String {
        if self.has_put() {
            match self.pattern.take() {
                ::std::option::Option::Some(api::Pattern::put(v)) => v,
                _ => panic!(),
            }
        } else {
            ::std::string::String::new()
        }
    }

    // string post = 50003;

    pub fn get_post(&self) -> &str {
        match self.pattern {
            ::std::option::Option::Some(api::Pattern::post(ref v)) => v,
            _ => "",
        }
    }

    pub fn clear_post(&mut self) {
        self.pattern = ::std::option::Option::None;
    }

    pub fn has_post(&self) -> bool {
        match self.pattern {
            ::std::option::Option::Some(api::Pattern::post(..)) => true,
            _ => false,
        }
    }

    // Param is passed by value, moved
    pub fn set_post(&mut self, v: ::std::string::String) {
        self.pattern = ::std::option::Option::Some(api::Pattern::post(v))
    }

    // Mutable pointer to the field.
    pub fn mut_post(&mut self) -> &mut ::std::string::String {
        if let ::std::option::Option::Some(api::Pattern::post(_)) = self.pattern {
        } else {
            self.pattern = ::std::option::Option::Some(api::Pattern::post(::std::string::String::new()));
        }
        match self.pattern {
            ::std::option::Option::Some(api::Pattern::post(ref mut v)) => v,
            _ => panic!(),
        }
    }

    // Take field
    pub fn take_post(&mut self) -> ::std::string::String {
        if self.has_post() {
            match self.pattern.take() {
                ::std::option::Option::Some(api::Pattern::post(v)) => v,
                _ => panic!(),
            }
        } else {
            ::std::string::String::new()
        }
    }

    // string delete = 50004;

    pub fn get_delete(&self) -> &str {
        match self.pattern {
            ::std::option::Option::Some(api::Pattern::delete(ref v)) => v,
            _ => "",
        }
    }

    pub fn clear_delete(&mut self) {
        self.pattern = ::std::option::Option::None;
    }

    pub fn has_delete(&self) -> bool {
        match self.pattern {
            ::std::option::Option::Some(api::Pattern::delete(..)) => true,
            _ => false,
        }
    }

    // Param is passed by value, moved
    pub fn set_delete(&mut self, v: ::std::string::String) {
        self.pattern = ::std::option::Option::Some(api::Pattern::delete(v))
    }

    // Mutable pointer to the field.
    pub fn mut_delete(&mut self) -> &mut ::std::string::String {
        if let ::std::option::Option::Some(api::Pattern::delete(_)) = self.pattern {
        } else {
            self.pattern = ::std::option::Option::Some(api::Pattern::delete(::std::string::String::new()));
        }
        match self.pattern {
            ::std::option::Option::Some(api::Pattern::delete(ref mut v)) => v,
            _ => panic!(),
        }
    }

    // Take field
    pub fn take_delete(&mut self) -> ::std::string::String {
        if self.has_delete() {
            match self.pattern.take() {
                ::std::option::Option::Some(api::Pattern::delete(v)) => v,
                _ => panic!(),
            }
        } else {
            ::std::string::String::new()
        }
    }

    // string patch = 50005;

    pub fn get_patch(&self) -> &str {
        match self.pattern {
            ::std::option::Option::Some(api::Pattern::patch(ref v)) => v,
            _ => "",
        }
    }

    pub fn clear_patch(&mut self) {
        self.pattern = ::std::option::Option::None;
    }

    pub fn has_patch(&self) -> bool {
        match self.pattern {
            ::std::option::Option::Some(api::Pattern::patch(..)) => true,
            _ => false,
        }
    }

    // Param is passed by value, moved
    pub fn set_patch(&mut self, v: ::std::string::String) {
        self.pattern = ::std::option::Option::Some(api::Pattern::patch(v))
    }

    // Mutable pointer to the field.
    pub fn mut_patch(&mut self) -> &mut ::std::string::String {
        if let ::std::option::Option::Some(api::Pattern::patch(_)) = self.pattern {
        } else {
            self.pattern = ::std::option::Option::Some(api::Pattern::patch(::std::string::String::new()));
        }
        match self.pattern {
            ::std::option::Option::Some(api::Pattern::patch(ref mut v)) => v,
            _ => panic!(),
        }
    }

    // Take field
    pub fn take_patch(&mut self) -> ::std::string::String {
        if self.has_patch() {
            match self.pattern.take() {
                ::std::option::Option::Some(api::Pattern::patch(v)) => v,
                _ => panic!(),
            }
        } else {
            ::std::string::String::new()
        }
    }

    fn generated_message_descriptor_data() -> ::protobuf::reflect::GeneratedMessageDescriptorData {
        let mut fields = ::std::vec::Vec::new();
        fields.push(::protobuf::reflect::rt::v2::make_simpler_field_accessor::<_, _>(
            "content_type",
            |m: &API| { &m.content_type },
            |m: &mut API| { &mut m.content_type },
        ));
        fields.push(::protobuf::reflect::rt::v2::make_oneof_deref_has_get_set_simpler_accessor::<_, _>(
            "get",
            API::has_get,
            API::get_get,
            API::set_get,
        ));
        fields.push(::protobuf::reflect::rt::v2::make_oneof_deref_has_get_set_simpler_accessor::<_, _>(
            "put",
            API::has_put,
            API::get_put,
            API::set_put,
        ));
        fields.push(::protobuf::reflect::rt::v2::make_oneof_deref_has_get_set_simpler_accessor::<_, _>(
            "post",
            API::has_post,
            API::get_post,
            API::set_post,
        ));
        fields.push(::protobuf::reflect::rt::v2::make_oneof_deref_has_get_set_simpler_accessor::<_, _>(
            "delete",
            API::has_delete,
            API::get_delete,
            API::set_delete,
        ));
        fields.push(::protobuf::reflect::rt::v2::make_oneof_deref_has_get_set_simpler_accessor::<_, _>(
            "patch",
            API::has_patch,
            API::get_patch,
            API::set_patch,
        ));
        ::protobuf::reflect::GeneratedMessageDescriptorData::new_2::<API>(
            "API",
            0,
            fields,
        )
    }
}

impl ::protobuf::Message for API {
    fn is_initialized(&self) -> bool {
        true
    }

    fn merge_from(&mut self, is: &mut ::protobuf::CodedInputStream<'_>) -> ::protobuf::ProtobufResult<()> {
        while !is.eof()? {
            let (field_number, wire_type) = is.read_tag_unpack()?;
            match field_number {
                50000 => {
                    if wire_type != ::protobuf::wire_format::WireTypeLengthDelimited {
                        return ::std::result::Result::Err(::protobuf::rt::unexpected_wire_type(wire_type));
                    }
                    self.content_type = is.read_string()?;
                },
                50001 => {
                    if wire_type != ::protobuf::wire_format::WireTypeLengthDelimited {
                        return ::std::result::Result::Err(::protobuf::rt::unexpected_wire_type(wire_type));
                    }
                    self.pattern = ::std::option::Option::Some(api::Pattern::get(is.read_string()?));
                },
                50002 => {
                    if wire_type != ::protobuf::wire_format::WireTypeLengthDelimited {
                        return ::std::result::Result::Err(::protobuf::rt::unexpected_wire_type(wire_type));
                    }
                    self.pattern = ::std::option::Option::Some(api::Pattern::put(is.read_string()?));
                },
                50003 => {
                    if wire_type != ::protobuf::wire_format::WireTypeLengthDelimited {
                        return ::std::result::Result::Err(::protobuf::rt::unexpected_wire_type(wire_type));
                    }
                    self.pattern = ::std::option::Option::Some(api::Pattern::post(is.read_string()?));
                },
                50004 => {
                    if wire_type != ::protobuf::wire_format::WireTypeLengthDelimited {
                        return ::std::result::Result::Err(::protobuf::rt::unexpected_wire_type(wire_type));
                    }
                    self.pattern = ::std::option::Option::Some(api::Pattern::delete(is.read_string()?));
                },
                50005 => {
                    if wire_type != ::protobuf::wire_format::WireTypeLengthDelimited {
                        return ::std::result::Result::Err(::protobuf::rt::unexpected_wire_type(wire_type));
                    }
                    self.pattern = ::std::option::Option::Some(api::Pattern::patch(is.read_string()?));
                },
                _ => {
                    ::protobuf::rt::read_unknown_or_skip_group(field_number, wire_type, is, self.mut_unknown_fields())?;
                },
            };
        }
        ::std::result::Result::Ok(())
    }

    // Compute sizes of nested messages
    #[allow(unused_variables)]
    fn compute_size(&self) -> u32 {
        let mut my_size = 0;
        if !self.content_type.is_empty() {
            my_size += ::protobuf::rt::string_size(50000, &self.content_type);
        }
        if let ::std::option::Option::Some(ref v) = self.pattern {
            match v {
                &api::Pattern::get(ref v) => {
                    my_size += ::protobuf::rt::string_size(50001, &v);
                },
                &api::Pattern::put(ref v) => {
                    my_size += ::protobuf::rt::string_size(50002, &v);
                },
                &api::Pattern::post(ref v) => {
                    my_size += ::protobuf::rt::string_size(50003, &v);
                },
                &api::Pattern::delete(ref v) => {
                    my_size += ::protobuf::rt::string_size(50004, &v);
                },
                &api::Pattern::patch(ref v) => {
                    my_size += ::protobuf::rt::string_size(50005, &v);
                },
            };
        }
        my_size += ::protobuf::rt::unknown_fields_size(self.get_unknown_fields());
        self.cached_size.set(my_size);
        my_size
    }

    fn write_to_with_cached_sizes(&self, os: &mut ::protobuf::CodedOutputStream<'_>) -> ::protobuf::ProtobufResult<()> {
        if !self.content_type.is_empty() {
            os.write_string(50000, &self.content_type)?;
        }
        if let ::std::option::Option::Some(ref v) = self.pattern {
            match v {
                &api::Pattern::get(ref v) => {
                    os.write_string(50001, v)?;
                },
                &api::Pattern::put(ref v) => {
                    os.write_string(50002, v)?;
                },
                &api::Pattern::post(ref v) => {
                    os.write_string(50003, v)?;
                },
                &api::Pattern::delete(ref v) => {
                    os.write_string(50004, v)?;
                },
                &api::Pattern::patch(ref v) => {
                    os.write_string(50005, v)?;
                },
            };
        }
        os.write_unknown_fields(self.get_unknown_fields())?;
        ::std::result::Result::Ok(())
    }

    fn get_cached_size(&self) -> u32 {
        self.cached_size.get()
    }

    fn get_unknown_fields(&self) -> &::protobuf::UnknownFields {
        &self.unknown_fields
    }

    fn mut_unknown_fields(&mut self) -> &mut ::protobuf::UnknownFields {
        &mut self.unknown_fields
    }

    fn new() -> API {
        API::new()
    }

    fn descriptor_static() -> ::protobuf::reflect::MessageDescriptor {
        ::protobuf::reflect::MessageDescriptor::new_generated_2(file_descriptor(), 0)
    }

    fn default_instance() -> &'static API {
        static instance: API = API {
            content_type: ::std::string::String::new(),
            pattern: ::std::option::Option::None,
            unknown_fields: ::protobuf::UnknownFields::new(),
            cached_size: ::protobuf::rt::CachedSize::new(),
        };
        &instance
    }
}

impl ::protobuf::Clear for API {
    fn clear(&mut self) {
        self.content_type.clear();
        self.pattern = ::std::option::Option::None;
        self.pattern = ::std::option::Option::None;
        self.pattern = ::std::option::Option::None;
        self.pattern = ::std::option::Option::None;
        self.pattern = ::std::option::Option::None;
        self.unknown_fields.clear();
    }
}

impl ::std::fmt::Debug for API {
    fn fmt(&self, f: &mut ::std::fmt::Formatter<'_>) -> ::std::fmt::Result {
        ::protobuf::text_format::fmt(self, f)
    }
}

impl ::protobuf::reflect::ProtobufValue for API {
    type RuntimeType = ::protobuf::reflect::runtime_types::RuntimeTypeMessage<Self>;
}

/// Nested message and enums of message `API`
pub mod api {

    #[derive(Clone,PartialEq,Debug)]
    pub enum Pattern {
        get(::std::string::String),
        put(::std::string::String),
        post(::std::string::String),
        delete(::std::string::String),
        patch(::std::string::String),
    }

    impl ::protobuf::Oneof for Pattern {
    }
}

/// Extension fields
pub mod exts {

    pub const name: ::protobuf::ext::ExtFieldOptional<::protobuf::descriptor::ServiceOptions, ::protobuf::reflect::types::ProtobufTypeString> = ::protobuf::ext::ExtFieldOptional { field_number: 50010, phantom: ::std::marker::PhantomData };

    pub const api: ::protobuf::ext::ExtFieldOptional<::protobuf::descriptor::MethodOptions, ::protobuf::reflect::types::ProtobufTypeMessage<super::API>> = ::protobuf::ext::ExtFieldOptional { field_number: 50011, phantom: ::std::marker::PhantomData };
}

static file_descriptor_proto_data: &'static [u8] = b"\
    \n\nhttp.proto\x12\x0bpandit.http\x1a\x20google/protobuf/descriptor.prot\
    o\"\xaf\x01\n\x03API\x12#\n\x0ccontent_type\x18\xd0\x86\x03\x20\x01(\tR\
    \x0bcontentType\x12\x14\n\x03get\x18\xd1\x86\x03\x20\x01(\tH\0R\x03get\
    \x12\x14\n\x03put\x18\xd2\x86\x03\x20\x01(\tH\0R\x03put\x12\x16\n\x04pos\
    t\x18\xd3\x86\x03\x20\x01(\tH\0R\x04post\x12\x1a\n\x06delete\x18\xd4\x86\
    \x03\x20\x01(\tH\0R\x06delete\x12\x18\n\x05patch\x18\xd5\x86\x03\x20\x01\
    (\tH\0R\x05patchB\t\n\x07pattern:5\n\x04name\x18\xda\x86\x03\x20\x01(\t\
    \x12\x1f.google.protobuf.ServiceOptionsR\x04name:D\n\x03api\x18\xdb\x86\
    \x03\x20\x01(\x0b2\x10.pandit.http.API\x12\x1e.google.protobuf.MethodOpt\
    ionsR\x03apiJ\x95\x07\n\x06\x12\x04\0\0\x20\x01\n\x08\n\x01\x0c\x12\x03\
    \0\0\x12\n\t\n\x02\x03\0\x12\x03\x01\x07)\n\x08\n\x01\x02\x12\x03\x03\
    \x08\x13\n\n\n\x02\x04\0\x12\x04\x05\0\x18\x01\n\n\n\x03\x04\0\x01\x12\
    \x03\x05\x08\x0b\n\x0b\n\x04\x04\0\x02\0\x12\x03\x06\x02\x1e\n\r\n\x05\
    \x04\0\x02\0\x04\x12\x04\x06\x02\x05\r\n\x0c\n\x05\x04\0\x02\0\x05\x12\
    \x03\x06\x02\x08\n\x0c\n\x05\x04\0\x02\0\x01\x12\x03\x06\t\x15\n\x0c\n\
    \x05\x04\0\x02\0\x03\x12\x03\x06\x18\x1d\n\x0c\n\x04\x04\0\x08\0\x12\x04\
    \x07\x02\x17\x03\n\x0c\n\x05\x04\0\x08\0\x01\x12\x03\x07\x08\x0f\n[\n\
    \x04\x04\0\x02\x01\x12\x03\n\x04\x17\x1aN\x20Maps\x20to\x20HTTP\x20GET.\
    \x20Used\x20for\x20listing\x20and\x20getting\x20information\x20about\n\
    \x20resources.\n\n\x0c\n\x05\x04\0\x02\x01\x05\x12\x03\n\x04\n\n\x0c\n\
    \x05\x04\0\x02\x01\x01\x12\x03\n\x0b\x0e\n\x0c\n\x05\x04\0\x02\x01\x03\
    \x12\x03\n\x11\x16\n?\n\x04\x04\0\x02\x02\x12\x03\r\x04\x17\x1a2\x20Maps\
    \x20to\x20HTTP\x20PUT.\x20Used\x20for\x20replacing\x20a\x20resource.\n\n\
    \x0c\n\x05\x04\0\x02\x02\x05\x12\x03\r\x04\n\n\x0c\n\x05\x04\0\x02\x02\
    \x01\x12\x03\r\x0b\x0e\n\x0c\n\x05\x04\0\x02\x02\x03\x12\x03\r\x11\x16\n\
    W\n\x04\x04\0\x02\x03\x12\x03\x10\x04\x18\x1aJ\x20Maps\x20to\x20HTTP\x20\
    POST.\x20Used\x20for\x20creating\x20a\x20resource\x20or\x20performing\
    \x20an\x20action.\n\n\x0c\n\x05\x04\0\x02\x03\x05\x12\x03\x10\x04\n\n\
    \x0c\n\x05\x04\0\x02\x03\x01\x12\x03\x10\x0b\x0f\n\x0c\n\x05\x04\0\x02\
    \x03\x03\x12\x03\x10\x12\x17\nA\n\x04\x04\0\x02\x04\x12\x03\x13\x04\x1a\
    \x1a4\x20Maps\x20to\x20HTTP\x20DELETE.\x20Used\x20for\x20deleting\x20a\
    \x20resource.\n\n\x0c\n\x05\x04\0\x02\x04\x05\x12\x03\x13\x04\n\n\x0c\n\
    \x05\x04\0\x02\x04\x01\x12\x03\x13\x0b\x11\n\x0c\n\x05\x04\0\x02\x04\x03\
    \x12\x03\x13\x14\x19\n@\n\x04\x04\0\x02\x05\x12\x03\x16\x04\x19\x1a3\x20\
    Maps\x20to\x20HTTP\x20PATCH.\x20Used\x20for\x20updating\x20a\x20resource\
    .\n\n\x0c\n\x05\x04\0\x02\x05\x05\x12\x03\x16\x04\n\n\x0c\n\x05\x04\0\
    \x02\x05\x01\x12\x03\x16\x0b\x10\n\x0c\n\x05\x04\0\x02\x05\x03\x12\x03\
    \x16\x13\x18\n\t\n\x01\x07\x12\x04\x1a\0\x1c\x01\n\t\n\x02\x07\0\x12\x03\
    \x1b\x02\x16\n\n\n\x03\x07\0\x02\x12\x03\x1a\x07%\n\x0b\n\x03\x07\0\x04\
    \x12\x04\x1b\x02\x1a'\n\n\n\x03\x07\0\x05\x12\x03\x1b\x02\x08\n\n\n\x03\
    \x07\0\x01\x12\x03\x1b\t\r\n\n\n\x03\x07\0\x03\x12\x03\x1b\x10\x15\n\t\n\
    \x01\x07\x12\x04\x1e\0\x20\x01\n\t\n\x02\x07\x01\x12\x03\x1f\x02\x12\n\n\
    \n\x03\x07\x01\x02\x12\x03\x1e\x07$\n\x0b\n\x03\x07\x01\x04\x12\x04\x1f\
    \x02\x1e'\n\n\n\x03\x07\x01\x06\x12\x03\x1f\x02\x05\n\n\n\x03\x07\x01\
    \x01\x12\x03\x1f\x06\t\n\n\n\x03\x07\x01\x03\x12\x03\x1f\x0c\x11b\x06pro\
    to3\
";

/// `FileDescriptorProto` object which was a source for this generated file
pub fn file_descriptor_proto() -> &'static ::protobuf::descriptor::FileDescriptorProto {
    static file_descriptor_proto_lazy: ::protobuf::rt::LazyV2<::protobuf::descriptor::FileDescriptorProto> = ::protobuf::rt::LazyV2::INIT;
    file_descriptor_proto_lazy.get(|| {
        ::protobuf::Message::parse_from_bytes(file_descriptor_proto_data).unwrap()
    })
}

/// `FileDescriptor` object which allows dynamic access to files
pub fn file_descriptor() -> ::protobuf::reflect::FileDescriptor {
    static file_descriptor_lazy: ::protobuf::rt::LazyV2<::protobuf::reflect::GeneratedFileDescriptor> = ::protobuf::rt::LazyV2::INIT;
    let file_descriptor = file_descriptor_lazy.get(|| {
        let mut deps = ::std::vec::Vec::new();
        deps.push(::protobuf::descriptor::file_descriptor());
        let mut messages = ::std::vec::Vec::new();
        messages.push(API::generated_message_descriptor_data());
        let mut enums = ::std::vec::Vec::new();
        ::protobuf::reflect::GeneratedFileDescriptor::new_generated(
            file_descriptor_proto(),
            deps,
            messages,
            enums,
        )
    });
    ::protobuf::reflect::FileDescriptor::new_generated_2(file_descriptor)
}
