apiVersion: v1
kind: Pod
metadata:
  name: pandit-example
spec:
  containers:
  - name: linux
    image: ubuntu:latest
    imagePullPolicy: Always
    resources:
      limits:
        cpu: "0.1"
        memory: 1000Mi
    ports:
    - containerPort: 6379
    args:
    - sleep
    - "604800"
    volumeMounts:
      - mountPath: /mnt/pandit
        name: host
  volumes:
    - hostPath:
        path: /pandit
      name: host
