apiVersion: v1
kind: Pod
metadata:
  name: pandit-example
spec:
  containers:
  - name: linux
    image: python:latest
    imagePullPolicy: Always
    resources:
      limits:
        cpu: "0.1"
        memory: 1000Mi
    ports:
    - containerPort: 6379
    args:
    - python
    - /mnt/pandit/src/proto/examples/example_rest.py
    volumeMounts:
      - mountPath: /mnt/pandit
        name: host
  volumes:
    - hostPath:
        path: /pandit
      name: host
---
apiVersion: v1
kind: Service
metadata:
  name: pandit-service
spec:
  selector:
    app: pandit-example
  ports:
    - protocol: TCP
      port: 8080
      targetPort: 8080
