// This file is generated by rust-protobuf 2.27.1. Do not edit
// @generated

// https://github.com/rust-lang/rust-clippy/issues/702
#![allow(unknown_lints)]
#![allow(clippy::all)]

#![allow(unused_attributes)]
#![cfg_attr(rustfmt, rustfmt::skip)]

#![allow(box_pointers)]
#![allow(dead_code)]
#![allow(missing_docs)]
#![allow(non_camel_case_types)]
#![allow(non_snake_case)]
#![allow(non_upper_case_globals)]
#![allow(trivial_casts)]
#![allow(unused_imports)]
#![allow(unused_results)]
//! Generated file from `api.proto`

/// Generated files are compatible only with the same version
/// of protobuf runtime.
// const _PROTOBUF_VERSION_CHECK: () = ::protobuf::VERSION_2_27_1;

#[derive(PartialEq,Clone,Default)]
pub struct StartServiceRequest {
    // message fields
    pub name: ::std::string::String,
    pub proto: ::std::vec::Vec<u8>,
    pub port: i32,
    // message oneof groups
    pub container: ::std::option::Option<StartServiceRequest_oneof_container>,
    // special fields
    pub unknown_fields: ::protobuf::UnknownFields,
    pub cached_size: ::protobuf::CachedSize,
}

impl<'a> ::std::default::Default for &'a StartServiceRequest {
    fn default() -> &'a StartServiceRequest {
        <StartServiceRequest as ::protobuf::Message>::default_instance()
    }
}

#[derive(Clone,PartialEq,Debug)]
pub enum StartServiceRequest_oneof_container {
    docker_id(::std::string::String),
    k8s_pod(::std::string::String),
    k8s_service(::std::string::String),
    k8s_replica_set(::std::string::String),
    k8s_stateful_set(::std::string::String),
}

impl StartServiceRequest {
    pub fn new() -> StartServiceRequest {
        ::std::default::Default::default()
    }

    // string name = 1;


    pub fn get_name(&self) -> &str {
        &self.name
    }
    pub fn clear_name(&mut self) {
        self.name.clear();
    }

    // Param is passed by value, moved
    pub fn set_name(&mut self, v: ::std::string::String) {
        self.name = v;
    }

    // Mutable pointer to the field.
    // If field is not initialized, it is initialized with default value first.
    pub fn mut_name(&mut self) -> &mut ::std::string::String {
        &mut self.name
    }

    // Take field
    pub fn take_name(&mut self) -> ::std::string::String {
        ::std::mem::replace(&mut self.name, ::std::string::String::new())
    }

    // bytes proto = 2;


    pub fn get_proto(&self) -> &[u8] {
        &self.proto
    }
    pub fn clear_proto(&mut self) {
        self.proto.clear();
    }

    // Param is passed by value, moved
    pub fn set_proto(&mut self, v: ::std::vec::Vec<u8>) {
        self.proto = v;
    }

    // Mutable pointer to the field.
    // If field is not initialized, it is initialized with default value first.
    pub fn mut_proto(&mut self) -> &mut ::std::vec::Vec<u8> {
        &mut self.proto
    }

    // Take field
    pub fn take_proto(&mut self) -> ::std::vec::Vec<u8> {
        ::std::mem::replace(&mut self.proto, ::std::vec::Vec::new())
    }

    // int32 port = 3;


    pub fn get_port(&self) -> i32 {
        self.port
    }
    pub fn clear_port(&mut self) {
        self.port = 0;
    }

    // Param is passed by value, moved
    pub fn set_port(&mut self, v: i32) {
        self.port = v;
    }

    // string docker_id = 4;


    pub fn get_docker_id(&self) -> &str {
        match self.container {
            ::std::option::Option::Some(StartServiceRequest_oneof_container::docker_id(ref v)) => v,
            _ => "",
        }
    }
    pub fn clear_docker_id(&mut self) {
        self.container = ::std::option::Option::None;
    }

    pub fn has_docker_id(&self) -> bool {
        match self.container {
            ::std::option::Option::Some(StartServiceRequest_oneof_container::docker_id(..)) => true,
            _ => false,
        }
    }

    // Param is passed by value, moved
    pub fn set_docker_id(&mut self, v: ::std::string::String) {
        self.container = ::std::option::Option::Some(StartServiceRequest_oneof_container::docker_id(v))
    }

    // Mutable pointer to the field.
    pub fn mut_docker_id(&mut self) -> &mut ::std::string::String {
        if let ::std::option::Option::Some(StartServiceRequest_oneof_container::docker_id(_)) = self.container {
        } else {
            self.container = ::std::option::Option::Some(StartServiceRequest_oneof_container::docker_id(::std::string::String::new()));
        }
        match self.container {
            ::std::option::Option::Some(StartServiceRequest_oneof_container::docker_id(ref mut v)) => v,
            _ => panic!(),
        }
    }

    // Take field
    pub fn take_docker_id(&mut self) -> ::std::string::String {
        if self.has_docker_id() {
            match self.container.take() {
                ::std::option::Option::Some(StartServiceRequest_oneof_container::docker_id(v)) => v,
                _ => panic!(),
            }
        } else {
            ::std::string::String::new()
        }
    }

    // string k8s_pod = 5;


    pub fn get_k8s_pod(&self) -> &str {
        match self.container {
            ::std::option::Option::Some(StartServiceRequest_oneof_container::k8s_pod(ref v)) => v,
            _ => "",
        }
    }
    pub fn clear_k8s_pod(&mut self) {
        self.container = ::std::option::Option::None;
    }

    pub fn has_k8s_pod(&self) -> bool {
        match self.container {
            ::std::option::Option::Some(StartServiceRequest_oneof_container::k8s_pod(..)) => true,
            _ => false,
        }
    }

    // Param is passed by value, moved
    pub fn set_k8s_pod(&mut self, v: ::std::string::String) {
        self.container = ::std::option::Option::Some(StartServiceRequest_oneof_container::k8s_pod(v))
    }

    // Mutable pointer to the field.
    pub fn mut_k8s_pod(&mut self) -> &mut ::std::string::String {
        if let ::std::option::Option::Some(StartServiceRequest_oneof_container::k8s_pod(_)) = self.container {
        } else {
            self.container = ::std::option::Option::Some(StartServiceRequest_oneof_container::k8s_pod(::std::string::String::new()));
        }
        match self.container {
            ::std::option::Option::Some(StartServiceRequest_oneof_container::k8s_pod(ref mut v)) => v,
            _ => panic!(),
        }
    }

    // Take field
    pub fn take_k8s_pod(&mut self) -> ::std::string::String {
        if self.has_k8s_pod() {
            match self.container.take() {
                ::std::option::Option::Some(StartServiceRequest_oneof_container::k8s_pod(v)) => v,
                _ => panic!(),
            }
        } else {
            ::std::string::String::new()
        }
    }

    // string k8s_service = 6;


    pub fn get_k8s_service(&self) -> &str {
        match self.container {
            ::std::option::Option::Some(StartServiceRequest_oneof_container::k8s_service(ref v)) => v,
            _ => "",
        }
    }
    pub fn clear_k8s_service(&mut self) {
        self.container = ::std::option::Option::None;
    }

    pub fn has_k8s_service(&self) -> bool {
        match self.container {
            ::std::option::Option::Some(StartServiceRequest_oneof_container::k8s_service(..)) => true,
            _ => false,
        }
    }

    // Param is passed by value, moved
    pub fn set_k8s_service(&mut self, v: ::std::string::String) {
        self.container = ::std::option::Option::Some(StartServiceRequest_oneof_container::k8s_service(v))
    }

    // Mutable pointer to the field.
    pub fn mut_k8s_service(&mut self) -> &mut ::std::string::String {
        if let ::std::option::Option::Some(StartServiceRequest_oneof_container::k8s_service(_)) = self.container {
        } else {
            self.container = ::std::option::Option::Some(StartServiceRequest_oneof_container::k8s_service(::std::string::String::new()));
        }
        match self.container {
            ::std::option::Option::Some(StartServiceRequest_oneof_container::k8s_service(ref mut v)) => v,
            _ => panic!(),
        }
    }

    // Take field
    pub fn take_k8s_service(&mut self) -> ::std::string::String {
        if self.has_k8s_service() {
            match self.container.take() {
                ::std::option::Option::Some(StartServiceRequest_oneof_container::k8s_service(v)) => v,
                _ => panic!(),
            }
        } else {
            ::std::string::String::new()
        }
    }

    // string k8s_replica_set = 7;


    pub fn get_k8s_replica_set(&self) -> &str {
        match self.container {
            ::std::option::Option::Some(StartServiceRequest_oneof_container::k8s_replica_set(ref v)) => v,
            _ => "",
        }
    }
    pub fn clear_k8s_replica_set(&mut self) {
        self.container = ::std::option::Option::None;
    }

    pub fn has_k8s_replica_set(&self) -> bool {
        match self.container {
            ::std::option::Option::Some(StartServiceRequest_oneof_container::k8s_replica_set(..)) => true,
            _ => false,
        }
    }

    // Param is passed by value, moved
    pub fn set_k8s_replica_set(&mut self, v: ::std::string::String) {
        self.container = ::std::option::Option::Some(StartServiceRequest_oneof_container::k8s_replica_set(v))
    }

    // Mutable pointer to the field.
    pub fn mut_k8s_replica_set(&mut self) -> &mut ::std::string::String {
        if let ::std::option::Option::Some(StartServiceRequest_oneof_container::k8s_replica_set(_)) = self.container {
        } else {
            self.container = ::std::option::Option::Some(StartServiceRequest_oneof_container::k8s_replica_set(::std::string::String::new()));
        }
        match self.container {
            ::std::option::Option::Some(StartServiceRequest_oneof_container::k8s_replica_set(ref mut v)) => v,
            _ => panic!(),
        }
    }

    // Take field
    pub fn take_k8s_replica_set(&mut self) -> ::std::string::String {
        if self.has_k8s_replica_set() {
            match self.container.take() {
                ::std::option::Option::Some(StartServiceRequest_oneof_container::k8s_replica_set(v)) => v,
                _ => panic!(),
            }
        } else {
            ::std::string::String::new()
        }
    }

    // string k8s_stateful_set = 8;


    pub fn get_k8s_stateful_set(&self) -> &str {
        match self.container {
            ::std::option::Option::Some(StartServiceRequest_oneof_container::k8s_stateful_set(ref v)) => v,
            _ => "",
        }
    }
    pub fn clear_k8s_stateful_set(&mut self) {
        self.container = ::std::option::Option::None;
    }

    pub fn has_k8s_stateful_set(&self) -> bool {
        match self.container {
            ::std::option::Option::Some(StartServiceRequest_oneof_container::k8s_stateful_set(..)) => true,
            _ => false,
        }
    }

    // Param is passed by value, moved
    pub fn set_k8s_stateful_set(&mut self, v: ::std::string::String) {
        self.container = ::std::option::Option::Some(StartServiceRequest_oneof_container::k8s_stateful_set(v))
    }

    // Mutable pointer to the field.
    pub fn mut_k8s_stateful_set(&mut self) -> &mut ::std::string::String {
        if let ::std::option::Option::Some(StartServiceRequest_oneof_container::k8s_stateful_set(_)) = self.container {
        } else {
            self.container = ::std::option::Option::Some(StartServiceRequest_oneof_container::k8s_stateful_set(::std::string::String::new()));
        }
        match self.container {
            ::std::option::Option::Some(StartServiceRequest_oneof_container::k8s_stateful_set(ref mut v)) => v,
            _ => panic!(),
        }
    }

    // Take field
    pub fn take_k8s_stateful_set(&mut self) -> ::std::string::String {
        if self.has_k8s_stateful_set() {
            match self.container.take() {
                ::std::option::Option::Some(StartServiceRequest_oneof_container::k8s_stateful_set(v)) => v,
                _ => panic!(),
            }
        } else {
            ::std::string::String::new()
        }
    }
}

impl ::protobuf::Message for StartServiceRequest {
    fn is_initialized(&self) -> bool {
        true
    }

    fn merge_from(&mut self, is: &mut ::protobuf::CodedInputStream<'_>) -> ::protobuf::ProtobufResult<()> {
        while !is.eof()? {
            let (field_number, wire_type) = is.read_tag_unpack()?;
            match field_number {
                1 => {
                    ::protobuf::rt::read_singular_proto3_string_into(wire_type, is, &mut self.name)?;
                },
                2 => {
                    ::protobuf::rt::read_singular_proto3_bytes_into(wire_type, is, &mut self.proto)?;
                },
                3 => {
                    if wire_type != ::protobuf::wire_format::WireTypeVarint {
                        return ::std::result::Result::Err(::protobuf::rt::unexpected_wire_type(wire_type));
                    }
                    let tmp = is.read_int32()?;
                    self.port = tmp;
                },
                4 => {
                    if wire_type != ::protobuf::wire_format::WireTypeLengthDelimited {
                        return ::std::result::Result::Err(::protobuf::rt::unexpected_wire_type(wire_type));
                    }
                    self.container = ::std::option::Option::Some(StartServiceRequest_oneof_container::docker_id(is.read_string()?));
                },
                5 => {
                    if wire_type != ::protobuf::wire_format::WireTypeLengthDelimited {
                        return ::std::result::Result::Err(::protobuf::rt::unexpected_wire_type(wire_type));
                    }
                    self.container = ::std::option::Option::Some(StartServiceRequest_oneof_container::k8s_pod(is.read_string()?));
                },
                6 => {
                    if wire_type != ::protobuf::wire_format::WireTypeLengthDelimited {
                        return ::std::result::Result::Err(::protobuf::rt::unexpected_wire_type(wire_type));
                    }
                    self.container = ::std::option::Option::Some(StartServiceRequest_oneof_container::k8s_service(is.read_string()?));
                },
                7 => {
                    if wire_type != ::protobuf::wire_format::WireTypeLengthDelimited {
                        return ::std::result::Result::Err(::protobuf::rt::unexpected_wire_type(wire_type));
                    }
                    self.container = ::std::option::Option::Some(StartServiceRequest_oneof_container::k8s_replica_set(is.read_string()?));
                },
                8 => {
                    if wire_type != ::protobuf::wire_format::WireTypeLengthDelimited {
                        return ::std::result::Result::Err(::protobuf::rt::unexpected_wire_type(wire_type));
                    }
                    self.container = ::std::option::Option::Some(StartServiceRequest_oneof_container::k8s_stateful_set(is.read_string()?));
                },
                _ => {
                    ::protobuf::rt::read_unknown_or_skip_group(field_number, wire_type, is, self.mut_unknown_fields())?;
                },
            };
        }
        ::std::result::Result::Ok(())
    }

    // Compute sizes of nested messages
    #[allow(unused_variables)]
    fn compute_size(&self) -> u32 {
        let mut my_size = 0;
        if !self.name.is_empty() {
            my_size += ::protobuf::rt::string_size(1, &self.name);
        }
        if !self.proto.is_empty() {
            my_size += ::protobuf::rt::bytes_size(2, &self.proto);
        }
        if self.port != 0 {
            my_size += ::protobuf::rt::value_size(3, self.port, ::protobuf::wire_format::WireTypeVarint);
        }
        if let ::std::option::Option::Some(ref v) = self.container {
            match v {
                &StartServiceRequest_oneof_container::docker_id(ref v) => {
                    my_size += ::protobuf::rt::string_size(4, &v);
                },
                &StartServiceRequest_oneof_container::k8s_pod(ref v) => {
                    my_size += ::protobuf::rt::string_size(5, &v);
                },
                &StartServiceRequest_oneof_container::k8s_service(ref v) => {
                    my_size += ::protobuf::rt::string_size(6, &v);
                },
                &StartServiceRequest_oneof_container::k8s_replica_set(ref v) => {
                    my_size += ::protobuf::rt::string_size(7, &v);
                },
                &StartServiceRequest_oneof_container::k8s_stateful_set(ref v) => {
                    my_size += ::protobuf::rt::string_size(8, &v);
                },
            };
        }
        my_size += ::protobuf::rt::unknown_fields_size(self.get_unknown_fields());
        self.cached_size.set(my_size);
        my_size
    }

    fn write_to_with_cached_sizes(&self, os: &mut ::protobuf::CodedOutputStream<'_>) -> ::protobuf::ProtobufResult<()> {
        if !self.name.is_empty() {
            os.write_string(1, &self.name)?;
        }
        if !self.proto.is_empty() {
            os.write_bytes(2, &self.proto)?;
        }
        if self.port != 0 {
            os.write_int32(3, self.port)?;
        }
        if let ::std::option::Option::Some(ref v) = self.container {
            match v {
                &StartServiceRequest_oneof_container::docker_id(ref v) => {
                    os.write_string(4, v)?;
                },
                &StartServiceRequest_oneof_container::k8s_pod(ref v) => {
                    os.write_string(5, v)?;
                },
                &StartServiceRequest_oneof_container::k8s_service(ref v) => {
                    os.write_string(6, v)?;
                },
                &StartServiceRequest_oneof_container::k8s_replica_set(ref v) => {
                    os.write_string(7, v)?;
                },
                &StartServiceRequest_oneof_container::k8s_stateful_set(ref v) => {
                    os.write_string(8, v)?;
                },
            };
        }
        os.write_unknown_fields(self.get_unknown_fields())?;
        ::std::result::Result::Ok(())
    }

    fn get_cached_size(&self) -> u32 {
        self.cached_size.get()
    }

    fn get_unknown_fields(&self) -> &::protobuf::UnknownFields {
        &self.unknown_fields
    }

    fn mut_unknown_fields(&mut self) -> &mut ::protobuf::UnknownFields {
        &mut self.unknown_fields
    }

    fn as_any(&self) -> &dyn (::std::any::Any) {
        self as &dyn (::std::any::Any)
    }
    fn as_any_mut(&mut self) -> &mut dyn (::std::any::Any) {
        self as &mut dyn (::std::any::Any)
    }
    fn into_any(self: ::std::boxed::Box<Self>) -> ::std::boxed::Box<dyn (::std::any::Any)> {
        self
    }

    fn descriptor(&self) -> &'static ::protobuf::reflect::MessageDescriptor {
        Self::descriptor_static()
    }

    fn new() -> StartServiceRequest {
        StartServiceRequest::new()
    }

    fn descriptor_static() -> &'static ::protobuf::reflect::MessageDescriptor {
        static descriptor: ::protobuf::rt::LazyV2<::protobuf::reflect::MessageDescriptor> = ::protobuf::rt::LazyV2::INIT;
        descriptor.get(|| {
            let mut fields = ::std::vec::Vec::new();
            fields.push(::protobuf::reflect::accessor::make_simple_field_accessor::<_, ::protobuf::types::ProtobufTypeString>(
                "name",
                |m: &StartServiceRequest| { &m.name },
                |m: &mut StartServiceRequest| { &mut m.name },
            ));
            fields.push(::protobuf::reflect::accessor::make_simple_field_accessor::<_, ::protobuf::types::ProtobufTypeBytes>(
                "proto",
                |m: &StartServiceRequest| { &m.proto },
                |m: &mut StartServiceRequest| { &mut m.proto },
            ));
            fields.push(::protobuf::reflect::accessor::make_simple_field_accessor::<_, ::protobuf::types::ProtobufTypeInt32>(
                "port",
                |m: &StartServiceRequest| { &m.port },
                |m: &mut StartServiceRequest| { &mut m.port },
            ));
            fields.push(::protobuf::reflect::accessor::make_singular_string_accessor::<_>(
                "docker_id",
                StartServiceRequest::has_docker_id,
                StartServiceRequest::get_docker_id,
            ));
            fields.push(::protobuf::reflect::accessor::make_singular_string_accessor::<_>(
                "k8s_pod",
                StartServiceRequest::has_k8s_pod,
                StartServiceRequest::get_k8s_pod,
            ));
            fields.push(::protobuf::reflect::accessor::make_singular_string_accessor::<_>(
                "k8s_service",
                StartServiceRequest::has_k8s_service,
                StartServiceRequest::get_k8s_service,
            ));
            fields.push(::protobuf::reflect::accessor::make_singular_string_accessor::<_>(
                "k8s_replica_set",
                StartServiceRequest::has_k8s_replica_set,
                StartServiceRequest::get_k8s_replica_set,
            ));
            fields.push(::protobuf::reflect::accessor::make_singular_string_accessor::<_>(
                "k8s_stateful_set",
                StartServiceRequest::has_k8s_stateful_set,
                StartServiceRequest::get_k8s_stateful_set,
            ));
            ::protobuf::reflect::MessageDescriptor::new_pb_name::<StartServiceRequest>(
                "StartServiceRequest",
                fields,
                file_descriptor_proto()
            )
        })
    }

    fn default_instance() -> &'static StartServiceRequest {
        static instance: ::protobuf::rt::LazyV2<StartServiceRequest> = ::protobuf::rt::LazyV2::INIT;
        instance.get(StartServiceRequest::new)
    }
}

impl ::protobuf::Clear for StartServiceRequest {
    fn clear(&mut self) {
        self.name.clear();
        self.proto.clear();
        self.port = 0;
        self.container = ::std::option::Option::None;
        self.container = ::std::option::Option::None;
        self.container = ::std::option::Option::None;
        self.container = ::std::option::Option::None;
        self.container = ::std::option::Option::None;
        self.unknown_fields.clear();
    }
}

impl ::std::fmt::Debug for StartServiceRequest {
    fn fmt(&self, f: &mut ::std::fmt::Formatter<'_>) -> ::std::fmt::Result {
        ::protobuf::text_format::fmt(self, f)
    }
}

impl ::protobuf::reflect::ProtobufValue for StartServiceRequest {
    fn as_ref(&self) -> ::protobuf::reflect::ReflectValueRef {
        ::protobuf::reflect::ReflectValueRef::Message(self)
    }
}

#[derive(PartialEq,Clone,Default)]
pub struct StartServiceReply {
    // special fields
    pub unknown_fields: ::protobuf::UnknownFields,
    pub cached_size: ::protobuf::CachedSize,
}

impl<'a> ::std::default::Default for &'a StartServiceReply {
    fn default() -> &'a StartServiceReply {
        <StartServiceReply as ::protobuf::Message>::default_instance()
    }
}

impl StartServiceReply {
    pub fn new() -> StartServiceReply {
        ::std::default::Default::default()
    }
}

impl ::protobuf::Message for StartServiceReply {
    fn is_initialized(&self) -> bool {
        true
    }

    fn merge_from(&mut self, is: &mut ::protobuf::CodedInputStream<'_>) -> ::protobuf::ProtobufResult<()> {
        while !is.eof()? {
            let (field_number, wire_type) = is.read_tag_unpack()?;
            match field_number {
                _ => {
                    ::protobuf::rt::read_unknown_or_skip_group(field_number, wire_type, is, self.mut_unknown_fields())?;
                },
            };
        }
        ::std::result::Result::Ok(())
    }

    // Compute sizes of nested messages
    #[allow(unused_variables)]
    fn compute_size(&self) -> u32 {
        let mut my_size = 0;
        my_size += ::protobuf::rt::unknown_fields_size(self.get_unknown_fields());
        self.cached_size.set(my_size);
        my_size
    }

    fn write_to_with_cached_sizes(&self, os: &mut ::protobuf::CodedOutputStream<'_>) -> ::protobuf::ProtobufResult<()> {
        os.write_unknown_fields(self.get_unknown_fields())?;
        ::std::result::Result::Ok(())
    }

    fn get_cached_size(&self) -> u32 {
        self.cached_size.get()
    }

    fn get_unknown_fields(&self) -> &::protobuf::UnknownFields {
        &self.unknown_fields
    }

    fn mut_unknown_fields(&mut self) -> &mut ::protobuf::UnknownFields {
        &mut self.unknown_fields
    }

    fn as_any(&self) -> &dyn (::std::any::Any) {
        self as &dyn (::std::any::Any)
    }
    fn as_any_mut(&mut self) -> &mut dyn (::std::any::Any) {
        self as &mut dyn (::std::any::Any)
    }
    fn into_any(self: ::std::boxed::Box<Self>) -> ::std::boxed::Box<dyn (::std::any::Any)> {
        self
    }

    fn descriptor(&self) -> &'static ::protobuf::reflect::MessageDescriptor {
        Self::descriptor_static()
    }

    fn new() -> StartServiceReply {
        StartServiceReply::new()
    }

    fn descriptor_static() -> &'static ::protobuf::reflect::MessageDescriptor {
        static descriptor: ::protobuf::rt::LazyV2<::protobuf::reflect::MessageDescriptor> = ::protobuf::rt::LazyV2::INIT;
        descriptor.get(|| {
            let fields = ::std::vec::Vec::new();
            ::protobuf::reflect::MessageDescriptor::new_pb_name::<StartServiceReply>(
                "StartServiceReply",
                fields,
                file_descriptor_proto()
            )
        })
    }

    fn default_instance() -> &'static StartServiceReply {
        static instance: ::protobuf::rt::LazyV2<StartServiceReply> = ::protobuf::rt::LazyV2::INIT;
        instance.get(StartServiceReply::new)
    }
}

impl ::protobuf::Clear for StartServiceReply {
    fn clear(&mut self) {
        self.unknown_fields.clear();
    }
}

impl ::std::fmt::Debug for StartServiceReply {
    fn fmt(&self, f: &mut ::std::fmt::Formatter<'_>) -> ::std::fmt::Result {
        ::protobuf::text_format::fmt(self, f)
    }
}

impl ::protobuf::reflect::ProtobufValue for StartServiceReply {
    fn as_ref(&self) -> ::protobuf::reflect::ReflectValueRef {
        ::protobuf::reflect::ReflectValueRef::Message(self)
    }
}

static file_descriptor_proto_data: &'static [u8] = b"\
    \n\tapi.proto\x12\x03api\"\x93\x02\n\x13StartServiceRequest\x12\x12\n\
    \x04name\x18\x01\x20\x01(\tR\x04name\x12\x14\n\x05proto\x18\x02\x20\x01(\
    \x0cR\x05proto\x12\x12\n\x04port\x18\x03\x20\x01(\x05R\x04port\x12\x1d\n\
    \tdocker_id\x18\x04\x20\x01(\tH\0R\x08dockerId\x12\x19\n\x07k8s_pod\x18\
    \x05\x20\x01(\tH\0R\x06k8sPod\x12!\n\x0bk8s_service\x18\x06\x20\x01(\tH\
    \0R\nk8sService\x12(\n\x0fk8s_replica_set\x18\x07\x20\x01(\tH\0R\rk8sRep\
    licaSet\x12*\n\x10k8s_stateful_set\x18\x08\x20\x01(\tH\0R\x0ek8sStateful\
    SetB\x0b\n\tcontainer\"\x13\n\x11StartServiceReply2I\n\x03API\x12B\n\x0c\
    StartService\x12\x18.api.StartServiceRequest\x1a\x16.api.StartServiceRep\
    ly\"\0b\x06proto3\
";

static file_descriptor_proto_lazy: ::protobuf::rt::LazyV2<::protobuf::descriptor::FileDescriptorProto> = ::protobuf::rt::LazyV2::INIT;

fn parse_descriptor_proto() -> ::protobuf::descriptor::FileDescriptorProto {
    ::protobuf::Message::parse_from_bytes(file_descriptor_proto_data).unwrap()
}

pub fn file_descriptor_proto() -> &'static ::protobuf::descriptor::FileDescriptorProto {
    file_descriptor_proto_lazy.get(|| {
        parse_descriptor_proto()
    })
}
